### ISSUE TITLE
"UnicodeEncodeError: charmap codec can't encode character \u21b5"

### ISSUE THREAD

**Issue by thethales** [Uzay-G/archivy#113]
Greetings !

After installing the application and trying to manually add a Bookmark, an _Internal 500 Error page_ is presentend, and the following error is listed at the command prompt instance running the app:

`"UnicodeEncodeError: charmap codec can't encode character \u21b5"` Thrown at:  [data.py line 70](https://github.com/Uzay-G/archivy/blob/master/archivy/data.py#L70)

Environment Settings:

`archivy==0.6.0`
`Windows 10 Single Language - PT-BR - Build (10.0.18363.1139)` 
`Python 3.9.0` or `Python 3.8.0`

Screenshot:
![Command Line Output](https://i.imgur.com/DVE8tcq.png)

While the following change will correct the issue, (by adding the enconding parameter on the _open()_ statement). I'm unsure of the exact root cause, and at the moment, if this is an acceptable solution:
(Since I'm unfamiliar with the project, as of yet,  I'm unable to offer a proper pull request, sorry)

```python
def create(contents, title, path=""):
    path_to_md_file = get_data_dir() / path / f"{secure_filename(title)}.md"
    #Previous Statment: with open(path_to_md_file, "w") as file:
    with open(path_to_md_file, "w", encoding="utf-8") as file:
        file.write(contents)
```
on [data.py line 69](https://github.com/Uzay-G/archivy/blob/master/archivy/data.py#L69)

**Comment by Uzay-G** [comment]
You're right! That'll fix it. I'll push a commit and make a new release with the change. Thanks :+1:

**Comment by Uzay-G** [comment]
This should be fixed in https://github.com/Uzay-G/archivy/commit/9f5ee30a6acfef29509db866badb4f257689e7a9. You can do `pip install --upgrade archivy` to update to the new version which should have this fixed :)
