### ISSUE TITLE
Unable to Expand Directories at Home, when OS Path (SEP) is '/' 

### ISSUE THREAD

**Issue by thethales** [Uzay-G/archivy#115]
Greetings,

I'm unable to use the _Expand_ button at the Home page due to a javascript parsing error:

`Uncaught SyntaxError: Invalid or unexpected token` [at base.html, line 160 ](https://github.com/Uzay-G/archivy/blob/9f5ee30a6acfef29509db866badb4f257689e7a9/archivy/templates/base.html#L160)  and  [base.html, line 177 ](https://github.com/Uzay-G/archivy/blob/9f5ee30a6acfef29509db866badb4f257689e7a9/archivy/templates/base.html#L160)

_Environment Settings:_

```
archivy==0.6.1
Windows 10 Single Language - PT-BR - Build (10.0.18363.1139)
Python 3.9.0
```

While I cannot confirm this issue to be a common occurrence throughout other environment setups, I was able to determine that the issue is raised only when  `os.path.sep = '\'`, which  will trigger the parsing error at the client side.

In my installation I corrected the issue by adding the replace function `{{SEP|replace('\\','\\' + '\\') }}` to escape the character, as follows. (Normally I would replace the value only once,  but I couldn't figure out the correct syntax for replacing variables in JINJA with the delimiters `{%..%}` ) (Which seems to be a [common doubt](https://groups.google.com/g/salt-users/c/0iC75dLeZUk/m/Y2bU12K7yVYJ), I would be very interested in the proper solution)

```javascript
async function createFolder(id)
    {
        max_folder_id++;
        let input = document.getElementById(`form-input-${id}`);
        let basePath = document.getElementById(`form-path-${id}`).textContent; 
        //Previous Statment:  let totalPath = basePath === "" ? [] : basePath.split("{{SEP}}");
        let totalPath = basePath === "" ? [] : basePath.split("{{SEP|replace('\\','\\' + '\\') }}");

```

and

```javascript
else {
    totalPath = await result.text();
    // get last element of totalPath
    //Previous Statment:  let sanitizedDirname = totalPath.split("{{SEP}}").slice(-1).pop();
    let sanitizedDirname = totalPath.split("{{SEP|replace('\\','\\' + '\\') }}").slice(-1).pop();
```

Those changes enabled the _Expand_ button in my archivy instance.

_Screenshot:_

![Screenshot](https://user-images.githubusercontent.com/7027160/96395696-acb3ce00-119b-11eb-83a7-60b45b4ef357.png)

**Comment by Uzay-G** [comment]
Thanks for finding this! we don't have much testing on windows :smile:. This should be fixed in https://github.com/Uzay-G/archivy/commit/43bfb00a96a04a20ed992ac177e4327892ecc927, where I changed the separator on the backend instead of in the jinja template. 

You can upgrade the archivy package for a fix :+1:
