### ISSUE TITLE
[FR] Add a sidebar to the UI

### ISSUE THREAD

**Issue by leram84** [Uzay-G/archivy#17]
The file tree would be much more accessible and intuitive as a sidebar imo. You could even still keep the existing tree in the main window if you want that type of experience when doing a live search, but having a much smaller font sidebar to quickly drill down when you have a lot of dirs would be much more efficient. And maybe a section in the sidebar above or under the filetree for the most popular tags along w a tag search box.

Absolutely love this app btw! Something I have wanted for years, so TY!

**Comment by Uzay-G** [comment]
> Absolutely love this app btw! Something I have wanted for years, so TY!

Thank you so much! :smile: 

For the sidebar you mean something on the side of every page and provide a minimal tree view?

We could remove the tree view from the homepage and then provide a more advanced ui in the main page (options to group pages by tag, etc...)

**Comment by leram84** [comment]
I think we're saying the same thing... I mean to have the entire ui broken into a sidebar/mainpage system. The sidebar would basically be everything you currently have from `root` down, but when you open pages it would just open them in the mainpage frame.

**Comment by Uzay-G** [comment]
Working on it: 
![random](https://user-images.githubusercontent.com/52892257/93272782-9b4f5e80-f7b6-11ea-8916-beef53bbb377.gif)
