### ISSUE TITLE
ADD: way of opening local file automatically once new note is created.

### ISSUE THREAD

**Issue by Uzay-G** [Uzay-G/archivy#3]
For example, I create a note on `Knowledge bases`. I will then have to open the generated file myself.

Figuring out a way to open this file in your specified editor automatically would improve the UX here.

**Comment by cktang88** [comment]
On Linux, you can use `xdg-open` to use whatever the user has as the default application for opening markdown files.

**Comment by Uzay-G** [comment]
Oh nice. I didn't think of that!

**Comment by Uzay-G** [comment]
Thanks for the advice. I Implemented it here: https://github.com/Uzay-G/archivy/commit/4afa0f1760166798139b1e5397cbdf44d3e71abf
