### ISSUE TITLE
Asan runtime issue

### ISSUE THREAD

**Issue by laoshaw** [Uzay-G/archivy#35]
On ubuntu 20.04 I could not run it, I got "==889789==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD."

**Comment by srevinsaju** [comment]
@laoshaw sorry for the delay, but
Can you test this, and see if it works

[archivy-x86_64.AppImage](https://transfersh.com/I7WfQ/archivy-x86_64.AppImage)

**Comment by laoshaw** [comment]
yes this one works. Thanks.

**Comment by srevinsaju** [comment]
@laoshaw the static files did not work on the old appimage. This one works https://transfersh.com/YmEz2/archivy-x86_64.AppImage

**Comment by laoshaw** [comment]
both worked for me. Thanks.

**Comment by Uzay-G** [comment]
Perfect! Thanks @srevinsaju

**Comment by Uzay-G** [comment]
I'll close this now. Please reopen if you have any other problems.
