### ISSUE TITLE
Add elastic-search to docker-compose?

### ISSUE THREAD

**Issue by cktang88** [Uzay-G/archivy#39]
Could the elastic-search image be added into the docker-compose file? Then we wouldn't have to install elasticsearch outside of docker and run both in order to run the app. We'd simply just start up the docker-compose and it'll have everything needed to run the app.

**Comment by Uzay-G** [comment]
@HarshaVardhanJ what do you think of this? We should also update the docker stuff to use the python package.

**Comment by HarshaVardhanJ** [comment]
Please check the `docker` branch. Also, there's a PR pending to it that contains various fixes and improvements.

**Comment by HarshaVardhanJ** [comment]
@cktang88 If you wish to use Archivy with Elasticseach, use the `docker-compose-with-elasticsearch.yml` file. If it isn't available in the `docker` branch of this repo, check [this repo](https://github.com/HarshaVardhanJ/archivy/tree/docker). This contains all the updated docker-related documentation as well.

**Comment by HarshaVardhanJ** [comment]
@Uzay-G I will be able to update the Docker image to use the python package only after you've updated the package to include the https://github.com/Uzay-G/archivy/commit/2d592a7bee88cb06e0e39558d9df4ac90fc0cdac fix.

**Comment by Uzay-G** [comment]
ill push a release tonight

**Comment by Uzay-G** [comment]
Alright the new release is up :tada:

**Comment by HarshaVardhanJ** [comment]
@Uzay-G Thanks. Will make a commit to the `docker` branch soon.

**Comment by HarshaVardhanJ** [comment]
@Uzay-G PR #24 is ready to be integrated with the `docker` branch, in my opinion. I've also updated the documentation to reflect the changes so far.

**Comment by HarshaVardhanJ** [comment]
@cktang88 If and when possible, please do take a look at the `docker-compose.yml` and `docker-compose-with-elasticsearch.yml` files in PR #24. It's also available at [this repo](https://github.com/HarshaVardhanJ/archivy/tree/docker). I've tested it locally and it works. Would appreciate some confirmation from your end as well.

**Comment by cktang88** [comment]
@HarshaVardhanJ tested locally just now, works for me, thanks!
