### ISSUE TITLE
Some links get turned into buttons

### ISSUE THREAD

**Issue by cktang88** [Uzay-G/archivy#41]
For example, this link: https://hbr.org/2020/02/how-to-leave-work-at-work

![image](https://user-images.githubusercontent.com/10319942/90989295-d1564580-e55e-11ea-931e-34cef10ff402.png)

gets turned into:
![image](https://user-images.githubusercontent.com/10319942/90989322-de733480-e55e-11ea-8fd2-fc2ecd750230.png)

The DOM looks like:
![image](https://user-images.githubusercontent.com/10319942/90989382-0bbfe280-e55f-11ea-97b1-5c23c3619c31.png)

**Comment by Uzay-G** [comment]
That's weird... What are the stylings for the button <a> tags?

**Comment by cktang88** [comment]
The computed styling (firefox dev tools):
![image](https://user-images.githubusercontent.com/10319942/90989473-9a346400-e55f-11ea-8920-b78d0dca8c18.png)

**Comment by cktang88** [comment]
It seems the difference between the buttons and the non-button links is that the button links are italicized... 
```markdown
[Elizabeth Grace
Saunders](/search?term=elizabeth%20grace%20saunders&search_type=search-all) is
a [time management coach](http://reallifee.com/coaching) and the founder of
[Real Life E Time Coaching & Speaking](http://www.reallifee.com/). She is
author of [_How to Invest Your Time Like Money_](http://www.amazon.com/Invest-
Your-Time-Like-Money-ebook/dp/B00RZZA64I/)and [_Divine Time
Management_](https://www.amazon.com/Divine-Time-Management-Replacing-
Alignment/dp/1478974362/ref=sr_1_1?ie=UTF8&qid=1497480147&sr=8-1&keywords=divine+time+management).
Find out more at [www.RealLifeE.com](http://www.RealLifeE.com).
```

**Comment by Uzay-G** [comment]
Oh I found the problem. Ill push a fix soon.

**Comment by Uzay-G** [comment]
I pushed a fix at https://github.com/Uzay-G/archivy/commit/01681e8fdd7f4c4e197f6b3f1629c39c2947cf03. Will be in the next release
