### ISSUE TITLE
feature request: bulk-import Chrome/Firefox bookmark exports

### ISSUE THREAD

**Issue by cktang88** [Uzay-G/archivy#43]
It would be useful to have a way to bulk-import chrome/FF bookmark exported HTML files.

Maybe use https://pypi.org/project/bookmarks-parser/ or just hand-parse.

**Comment by Uzay-G** [comment]
Saving this library also: https://github.com/FlyingWolFox/Netscape-Bookmarks-File-Parser.

I'll work on this feature once we finish up with some other milestones :+1:

**Comment by Uzay-G** [comment]
Idea to implement once we have https://github.com/Uzay-G/archivy/issues/86. Closing for now.
