### ISSUE TITLE
Error when adding note in version 0.0.7

### ISSUE THREAD

**Issue by HarshaVardhanJ** [Uzay-G/archivy#48]
When I try to add a note, here's the error I get:
```
Setting environment variables.
The following environment variables were set:
		FLASK_DEBUG=1
		ELASTICSEARCH_ENABLED=0
		ELASTICSEARCH_URL=http://localhost:9200/
Elasticsearch not used. Search function will not work.
Starting Archivy
 * Serving Flask app "archivy" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with inotify reloader
 * Debugger is active!
 * Debugger PIN: 149-720-253
172.17.0.1 - - [25/Aug/2020 09:39:43] "GET /index HTTP/1.1" 200 -
172.17.0.1 - - [25/Aug/2020 09:40:06] "GET /notes/new HTTP/1.1" 200 -
172.17.0.1 - - [25/Aug/2020 09:40:16] "POST /notes/new HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 2450, in wsgi_app
    response = self.handle_exception(e)
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 1867, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/archivy/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/archivy/.local/lib/python3.8/site-packages/archivy/routes.py", line 64, in new_note
    note_id = note.insert()
  File "/home/archivy/.local/lib/python3.8/site-packages/archivy/models.py", line 116, in insert
    self.fullpath = create(
  File "/home/archivy/.local/lib/python3.8/site-packages/archivy/data.py", line 69, in create
    open_file(path_to_md_file)
  File "/home/archivy/.local/lib/python3.8/site-packages/archivy/data.py", line 113, in open_file
    subprocess.Popen(["xdg-open", path])
  File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'xdg-open'
172.17.0.1 - - [25/Aug/2020 09:40:17] "GET /notes/new?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
172.17.0.1 - - [25/Aug/2020 09:40:17] "GET /notes/new?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
172.17.0.1 - - [25/Aug/2020 09:40:17] "GET /notes/new?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
172.17.0.1 - - [25/Aug/2020 09:40:17] "GET /notes/new?__debugger__=yes&cmd=resource&f=ubuntu.ttf HTTP/1.1" 200 -
172.17.0.1 - - [25/Aug/2020 09:40:17] "GET /notes/new?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

But when I view the Home page, I can see that two notes were created. The notes are being created, but this error is displayed on the page.

**Comment by Uzay-G** [comment]
what platform are you running this on?

I added something so the file would open when you create a note and it should work in mac, windows and unix. If you're running it on a server it might be a problem though...

**Comment by Uzay-G** [comment]
Do you have any idea what we should do so it doesn't open in this case?

**Comment by HarshaVardhanJ** [comment]
> what platform are you running this on?
> 
> I added something so the file would open when you create a note and it should work in mac, windows and unix. If you're running it on a server it might be a problem though...

I see. That could be it. I'm running Archivy in a container(Docker for Mac) and am accessing it on a Mac.

**Comment by HarshaVardhanJ** [comment]
> Do you have any idea what we should do so it doesn't open in this case?

I don't have the `xdg-open` program on my Mac. And neither is it present in the container image.
I don't know how else you could open the file in the browser. I'll get back to you on this.

**Comment by Uzay-G** [comment]
> > Do you have any idea what we should do so it doesn't open in this case?
> 
> I don't have the `xdg-open` program on my Mac. And neither is it present in the container image.
> I don't know how else you could open the file in the browser. I'll get back to you on this.

On the mac it should call the `open` command. It checks the platform.

Could you try running this in python:

```python
import platform
print(platform.system())
```

This will tell us which platform your computer is on. Archivy uses this to check if it's a mac. If it is, the output should be "Darwin".

**Comment by HarshaVardhanJ** [comment]
> > > Do you have any idea what we should do so it doesn't open in this case?
> > 
> > 
> > I don't have the `xdg-open` program on my Mac. And neither is it present in the container image.
> > I don't know how else you could open the file in the browser. I'll get back to you on this.
> 
> On the mac it should call the `open` command. Archivy checks the platform and uses the right command.
> 
> Could you try running this in python:
> 
> ```python
> import platform
> print(platform.system())
> ```
> 
> This will tell us which platform your computer is on. Archivy uses this to check if it's a mac. If it is, the output should be "Darwin".

Ah. I see what you mean. The container is built on a base image of Alpine Linux. I'll add `xdg-utils` to be installed. That should fix it.

**Comment by HarshaVardhanJ** [comment]
I get this error now:
```
172.17.0.1 - - [25/Aug/2020 09:59:01] "POST /notes/new HTTP/1.1" 302 -
/usr/bin/xdg-open: line 881: www-browser: not found
/usr/bin/xdg-open: line 881: links2: not found
/usr/bin/xdg-open: line 881: elinks: not found
/usr/bin/xdg-open: line 881: links: not found
/usr/bin/xdg-open: line 881: lynx: not found
/usr/bin/xdg-open: line 881: w3m: not found
xdg-open: no method available for opening '/home/archivy/.local/share/archivy/data/1-08-25-20-Test.md'
```

I'll install `elinks` and try again.

**Comment by Uzay-G** [comment]
You might not even have an editor on the image.

**Comment by HarshaVardhanJ** [comment]
Right. Just figured that out. This feature may not work inside a container. Any thoughts on what to do?

**Comment by HarshaVardhanJ** [comment]
What about [Trix](https://trix-editor.org)?

**Comment by Uzay-G** [comment]
Something like that will be good. We will implement a Web editor and an
option for local editing.

**Comment by HarshaVardhanJ** [comment]
Sounds good.

**Comment by HarshaVardhanJ** [comment]
Shall I close this issue for now, then?

**Comment by Uzay-G** [comment]
Yes i'll close it. Please put your suggestions in https://github.com/Uzay-G/archivy/issues/33 where we've already started thinking about this problem.
