### ISSUE TITLE
Obsidian app markdown search

### ISSUE THREAD

**Issue by dxcore35** [Uzay-G/archivy#50]
Why you don't join the devs in https://obsidian.md project? All markdown files are fully searchable, but I think you can help them to get the speed up :)

**Comment by clemux** [comment]
Obsidian does not seem to be open-source, see https://obsidian.md/eula and https://github.com/obsidianmd/

**Comment by Uzay-G** [comment]
Thanks! But like @clemux pointed out. They're not open source and I doubt they would agree.
