### ISSUE TITLE
ADD: REST API for managing bookmarks

### ISSUE THREAD

**Issue by clemux** [Uzay-G/archivy#62]
It would be useful to add an API to manage bookmarks, for example:

 - `GET /bookmarks` -> retrieve all the bookmarks (with optional filters)
 - `GET /bookmarks/2` -> retrieve bookmark 2
 - `POST /bookmarks` -> create new bookmark
 - `PUT /bookmarks/2` -> modify bookmark 2
 - `DELETE /bookmarks/2` -> delete bookmark 2

In the short-term, the POST endpoint would be most useful, since it would allow easy integration with browsers and other applications. It would also allow easier testing of various functionalities (asynchronous processing, new importers, changes to data model, etc.)

In the longer run, it will allow more dynamic user interfaces.

**Comment by cktang88** [comment]
> allow more dynamic user interfaces.
+ 1 to this, ideally people would be able to write their own frontends, and this could be frontend-agnostic. Personally I'd prefer React, which makes interactivity a LOT easier.

**Comment by Uzay-G** [comment]
Often NPM packages can be imported without having to use React or a js backend, but I see what you mean.
