### ISSUE TITLE
Markdown files not recognized

### ISSUE THREAD

**Issue by dxcore35** [Uzay-G/archivy#64]
I have copied proper markdown files in side project folder. I can see the records but I cannot open the file in Archivy.
I can see only this:

![Screenshot 2020-08-29 at 09 43 28](https://user-images.githubusercontent.com/7279156/91628100-97fc5a80-e9e2-11ea-8753-79b5768165e4.jpg)

**Comment by HarshaVardhanJ** [comment]
Can you paste the full path of the folder to which you copied the files? Also, which OS are you running this on?

**Comment by Uzay-G** [comment]
The way markdown files work in Archivy is that each file has a few metadata attributes. Structure of a markdown file:

```md
---
title: ...
tags: []
...
---

content
```

I assume the files here don't have that title attribute and so we can't see the title in the ui.

**Comment by dxcore35** [comment]
/Users/USER/Library/Application\ Support/archivy/data/

Of course there are no tags, there is no mention of tags in description.... Why you don't make it for file without this prefix title just file name?

**Comment by Uzay-G** [comment]
That could work, but the problem is that each markdown file has an `id`, that is how archivy knows to get the fileid `x` when you visit `/dataobjs/id`. This is also in the title of the markdown file.

What we could do is add some sort of bulk import function :thinking:

**Comment by dxcore35** [comment]
Bulk function will be perfect! I think many people will rather import files then write them directly in database.
I consider your tool for reading the information, not writing them...

**Comment by Uzay-G** [comment]
Moved to https://github.com/Uzay-G/archivy/issues/68
