### ISSUE TITLE
[Important] Testing

### ISSUE THREAD

**Issue by Uzay-G** [Uzay-G/archivy#67]
@clemux has tested pocket functionality in the `integration/test_pocket.py` file and I have also tested the models in `unit/test_models.py`. 

What parts of the app should we focus on for testing because they are prone to break?

**Comment by clemux** [comment]
I think aiming towards 100% code coverage is a reasonable goal. Speaking of which, could you enable code coverage reports in the CI?

To get there, I would suggest:

- every new feature should be covered by tests
- every bug fix should be covered by tests 
- before starting a refactoring, tests should be written to avoid any regression (that's actually why I started the pocket tests)
