### ISSUE TITLE
Bulk function for importing non-formatted markdown files

### ISSUE THREAD

**Issue by Uzay-G** [Uzay-G/archivy#68]
Would allow user to specify a directory path, where each .md file in it would be converted to a archivy-compliant format.

**Comment by dxcore35** [comment]
I just want to add that import should be pain free for user. The best is to just copy markdowns into folder, and let the database handle and add the header.

Please consider that tool should be flexible for new content and not rigid, and do not requite any action from user.

**Comment by Uzay-G** [comment]
Alright I think I know a way to do it without user effort.

**Comment by Uzay-G** [comment]
I recently pushed fixes that allow you to move random markdown files and they will automatically get formatted correctly for archivy and get added to the knowledge base. Will be available on the next release.

**Comment by dxcore35** [comment]
I will test it an let you know!

**Comment by Uzay-G** [comment]
Thanks! @clemux Do you know how to fix the flake8 errors with the regex?

**Comment by dxcore35** [comment]
flake8? Im good in regex.

**Comment by clemux** [comment]
> Thanks! @clemux Do you know how to fix the flake8 errors with the regex?

There: https://github.com/Uzay-G/archivy/pull/71

**Comment by dxcore35** [comment]
I don't understand the activity there :/

**Comment by Uzay-G** [comment]
What do you mean?

**Comment by dxcore35** [comment]
i have check the link, and I don't understand the context of the ticket. The scrip should simply add header, filling the tile from file name... I think this is not difficult to do. And if this works for one file it should work for all files....if not then it is over-engineered :)

**Comment by Uzay-G** [comment]
Basically what it currently does is if u move a file to the dir, it will be automatically converted to archivy format. I just noticed a bug though where this will only happen if elasticsearch is enabled. I need to fix that

**Comment by dxcore35** [comment]
I dont understand your approach... Archivy format? It should be still just plain markdown with header thats it.

**Comment by Uzay-G** [comment]
Archivy format means the file is structured like this

{Id}-{date}-{filename}.md

And then we have some values in the metadata . That's all I mean.

**Comment by dxcore35** [comment]
I hope metadata are adding standard YAML header.

**Comment by Uzay-G** [comment]
Yes that's what I mean

**Comment by Uzay-G** [comment]
Pushed in the new release :+1:
