### ISSUE TITLE
Unable to run on local machine even after having all requirements

### ISSUE THREAD

**Issue by godslayer201** [Uzay-G/archivy#75]

**Comment by HarshaVardhanJ** [comment]
Could you post the output of the following commands?

- `uname -a`
- `which python`
- `which pip`
- `python --version`
- `pip --version`

Also, can you post the output of 

- `pip install archivy==0.0.8`

**Comment by godslayer201** [comment]
Yes Harsha,I'll run them and check,thank you for the headsup. attaching results.

The first 3 were unrecognized commands,but pip and python displayed my versions(latest). The installation was successful,and i was able to run a production server.

What do you suggest to do next?
Thank you.

**Comment by HarshaVardhanJ** [comment]
You're able to run the application now?
By the way, are you running this on a Windows system?

**Comment by HarshaVardhanJ** [comment]
After running the application in the terminal, you should see something like this:
```
Starting Archivy
 * Serving Flask app "archivy" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
```

Now open `http://localhost:5000/` in your browser. You should see Archivy's UI now.

**Comment by godslayer201** [comment]
Works like a charm,thank you very much. will join your discord to learn and contribute!
