### ISSUE TITLE
[Feature] Add syntax highlighting

### ISSUE THREAD

**Issue by sakharovaan** [Uzay-G/archivy#77]
like
```
` ` `yaml
a: 5
b: hello
` ` `
(without spaces)
```
becomes

```yaml
a: 5
b: hello
```
since you are using the markdown library, this feature could be implemented via https://python-markdown.github.io/extensions/code_hilite/

I could make a PR, if you're okay with this implementation

**Comment by Uzay-G** [comment]
This is a good idea! We're actually switching to a more powerful markdown parser that supports footnotes, LaTeX and tons of other features. I'll implement syntax highlighting with it :ok_hand:

**Comment by Uzay-G** [comment]
The new release adds support for this :ok_hand:
