### ISSUE TITLE
"OSError: Adress already in use"

### ISSUE THREAD

**Issue by Minabsapi** [Uzay-G/archivy#94]
I just installed archivy from PIP and launched it for the first time. When I launch it I'm greeted with a long traceback followed by
``OSError: [Errno 98] Adress already in use``

Obviously another application is already using the port archivy wanted. But how can I tell archivy to use another one ? It seems I can't pass any option and there's no configuration I can edit to change this behavior

**Comment by Uzay-G** [comment]
Alright I'll implement a fix for this to work :+1:!

**Comment by Uzay-G** [comment]
I just fixed this in the last release (https://github.com/Uzay-G/archivy/commit/6699067dde1520e9b2fbc5617793e44832e1a9b0).

Just reinstall archivy through pip so you have the updated version and then do:

```
ARCHIVY_PORT=xxxx archivy
```
