### ISSUE TITLE
Where is the search button?

### ISSUE THREAD

**Issue by dxcore35** [Uzay-G/archivy#95]
**System:** Mac OS, Opera
**Installation:** fresh pip3

![Screenshot 2020-09-27 at 21 59 08](https://user-images.githubusercontent.com/7279156/94368920-da61a600-010c-11eb-8a42-4fb471173bf2.jpg)

**Comment by Uzay-G** [comment]
When you launch archivy, you need to set `ELASTICSEARCH_ENABLED=1` to specify that you have elasticsearch running so that search works.

For example you could run: 
`ELASTICSEARCH_ENABLED=1 archivy`

**Comment by dxcore35** [comment]
Brother, who will ever need this GUI without search?
