### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by dxcore35** [Uzay-G/archivy#96]
Screenshot from file you can see word: **Slovo**
![Screenshot 2020-09-27 at 22 16 03](https://user-images.githubusercontent.com/7279156/94369339-27467c00-010f-11eb-8889-3b7dfc232702.jpg)

This is search result, when pressing enter:
![Screenshot 2020-09-27 at 22 16 12](https://user-images.githubusercontent.com/7279156/94369336-2281c800-010f-11eb-8bc2-0cbf9fab35dc.jpg)

There are no results.... elastic search running correctly...

**Comment by Uzay-G** [comment]
Are u sure elasticsearch is running correctly? Also I noticed your other issue, you need to make sure you have specified that elasticsearch is enabled WHEN you create the note or bookmark otherwise it will not be indexed. 

If this was not the case, you can for example edit the notes while archivy is running with elasticsearch enabled and it will save them in Elasticsearch.

**Comment by dxcore35** [comment]
Yes. the elastic search runs correctly otherwise I cannot run: ```ELASTICSEARCH_ENABLED=1 archivy```
Now even the files name are not modified... Brother I give up with your software. There are so many problems with basic functionality.... I suggest for you to test the software, the basic things should work 100%, before you start to adding new features or even consider to adding them. :(

**Comment by HarshaVardhanJ** [comment]
@dxcore35 Are you sure that Elasticsearch is up and running? Elasticsearch takes some time to initialise and start up.

Could you post the output of the following command?

```sh
curl -XGET http://localhost:9200/
```

**Comment by Uzay-G** [comment]
> Yes. the elastic search runs correctly otherwise I cannot run: `ELASTICSEARCH_ENABLED=1 archivy`
> Now even the files name are not modified... Brother I give up with your software. There are so many problems with basic functionality.... I suggest for you to test the software, the basic things should work 100%, before you start to adding new features or even consider to adding them. :(

Once again:

> You need to make sure you have specified that elasticsearch is enabled WHEN you create the note or bookmark otherwise it will not be indexed.

> If this was not the case, you can for example edit the notes while archivy is running with elasticsearch enabled and it will save them in Elasticsearch if they were not already synced.

This is the first time someone mentions issue with ES.
